/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectodeprogra2;

import java.util.ArrayList;
import proyectodeprogra2.Personas.Cliente;

/**
 *
 * @author davidbendeck
 */
public class Vehiculos extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public Vehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_LogIn = new javax.swing.JDialog();
        P_LogIn = new javax.swing.JPanel();
        L_Nickname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF_Nickname = new javax.swing.JTextField();
        PF_Password = new javax.swing.JPasswordField();
        S_Usuario = new javax.swing.JSpinner();
        D_RegisterNaA = new javax.swing.JDialog();
        P_RegisterNaA = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_Nickname_RegisterNaA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PF_password_RegisterNaA = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        L_PaisDeNacimiento_RegisterNaA = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        DC_Birthday_RegisterNaA = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        TF_Correo_RegisterNaA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TF_NombreCompleto_RegisterNaA = new javax.swing.JTextField();
        B_Register_RegisterNaA = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        S_Usuario_RegisterNaA = new javax.swing.JSpinner();
        D_RetrievePassword = new javax.swing.JDialog();
        P_RetrievePassword = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TF_Correo_RetrievePassword = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        L_Password_RetrievePassword = new javax.swing.JLabel();
        D_MembresiaOfertador = new javax.swing.JDialog();
        P_MembresiaOfertador = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        B_LogIn = new javax.swing.JButton();
        L_SignIn = new javax.swing.JLabel();
        B_Register = new javax.swing.JButton();

        L_Nickname.setText("Nickname");

        jLabel2.setText("Contraseña");

        jLabel3.setText("Log In");

        javax.swing.GroupLayout P_LogInLayout = new javax.swing.GroupLayout(P_LogIn);
        P_LogIn.setLayout(P_LogInLayout);
        P_LogInLayout.setHorizontalGroup(
            P_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_LogInLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(P_LogInLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(P_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Nickname)
                    .addComponent(jLabel2))
                .addGap(86, 86, 86)
                .addGroup(P_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Nickname, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(PF_Password)))
        );
        P_LogInLayout.setVerticalGroup(
            P_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_LogInLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addGroup(P_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_Nickname)
                    .addComponent(TF_Nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(P_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout D_LogInLayout = new javax.swing.GroupLayout(D_LogIn.getContentPane());
        D_LogIn.getContentPane().setLayout(D_LogInLayout);
        D_LogInLayout.setHorizontalGroup(
            D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_LogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(S_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        D_LogInLayout.setVerticalGroup(
            D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_LogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(D_LogInLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(S_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Registrarse");

        jLabel4.setText("Nickname");

        jLabel5.setText("Password");

        PF_password_RegisterNaA.setText("jPasswordField1");

        jLabel6.setText("Pais de Nacimiento");

        L_PaisDeNacimiento_RegisterNaA.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(L_PaisDeNacimiento_RegisterNaA);

        jLabel7.setText("Fecha de nacimiento");

        jLabel8.setText("Correo");

        jLabel9.setText("Nombre completo");

        B_Register_RegisterNaA.setText("Registrarse");

        jLabel10.setText("Tipo de usuario");

        javax.swing.GroupLayout P_RegisterNaALayout = new javax.swing.GroupLayout(P_RegisterNaA);
        P_RegisterNaA.setLayout(P_RegisterNaALayout);
        P_RegisterNaALayout.setHorizontalGroup(
            P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_RegisterNaALayout.createSequentialGroup()
                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, P_RegisterNaALayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, P_RegisterNaALayout.createSequentialGroup()
                                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TF_NombreCompleto_RegisterNaA, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                        .addComponent(TF_Correo_RegisterNaA))
                                    .addComponent(DC_Birthday_RegisterNaA, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(S_Usuario_RegisterNaA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, P_RegisterNaALayout.createSequentialGroup()
                                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(41, 41, 41)
                                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(PF_password_RegisterNaA)
                                    .addComponent(TF_Nickname_RegisterNaA))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(P_RegisterNaALayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(22, 22, 22)
                .addComponent(B_Register_RegisterNaA)
                .addGap(138, 138, 138))
        );
        P_RegisterNaALayout.setVerticalGroup(
            P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_RegisterNaALayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TF_Nickname_RegisterNaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PF_password_RegisterNaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_RegisterNaALayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8))
                    .addGroup(P_RegisterNaALayout.createSequentialGroup()
                        .addComponent(DC_Birthday_RegisterNaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF_Correo_RegisterNaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TF_NombreCompleto_RegisterNaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(P_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Register_RegisterNaA)
                    .addComponent(jLabel10)
                    .addComponent(S_Usuario_RegisterNaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout D_RegisterNaALayout = new javax.swing.GroupLayout(D_RegisterNaA.getContentPane());
        D_RegisterNaA.getContentPane().setLayout(D_RegisterNaALayout);
        D_RegisterNaALayout.setHorizontalGroup(
            D_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_RegisterNaALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_RegisterNaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_RegisterNaALayout.setVerticalGroup(
            D_RegisterNaALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_RegisterNaALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_RegisterNaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setText("Recuperar Contraseña");

        jLabel12.setText("Ingrese su correo");

        TF_Correo_RetrievePassword.setText("jTextField1");

        jLabel13.setText("Su contraseña es:");

        L_Password_RetrievePassword.setText("Lol xdxdxd");

        javax.swing.GroupLayout P_RetrievePasswordLayout = new javax.swing.GroupLayout(P_RetrievePassword);
        P_RetrievePassword.setLayout(P_RetrievePasswordLayout);
        P_RetrievePasswordLayout.setHorizontalGroup(
            P_RetrievePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_RetrievePasswordLayout.createSequentialGroup()
                .addGroup(P_RetrievePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_RetrievePasswordLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel11))
                    .addGroup(P_RetrievePasswordLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(P_RetrievePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(68, 68, 68)
                        .addGroup(P_RetrievePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(L_Password_RetrievePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_Correo_RetrievePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        P_RetrievePasswordLayout.setVerticalGroup(
            P_RetrievePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_RetrievePasswordLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addGap(81, 81, 81)
                .addGroup(P_RetrievePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TF_Correo_RetrievePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(P_RetrievePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(L_Password_RetrievePassword))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout D_RetrievePasswordLayout = new javax.swing.GroupLayout(D_RetrievePassword.getContentPane());
        D_RetrievePassword.getContentPane().setLayout(D_RetrievePasswordLayout);
        D_RetrievePasswordLayout.setHorizontalGroup(
            D_RetrievePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_RetrievePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_RetrievePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        D_RetrievePasswordLayout.setVerticalGroup(
            D_RetrievePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_RetrievePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_RetrievePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel14.setText("Elija una membresía");

        jLabel15.setText("Tipo de membresia");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel16.setText("Realice su pago: ");

        javax.swing.GroupLayout P_MembresiaOfertadorLayout = new javax.swing.GroupLayout(P_MembresiaOfertador);
        P_MembresiaOfertador.setLayout(P_MembresiaOfertadorLayout);
        P_MembresiaOfertadorLayout.setHorizontalGroup(
            P_MembresiaOfertadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MembresiaOfertadorLayout.createSequentialGroup()
                .addGroup(P_MembresiaOfertadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_MembresiaOfertadorLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel14))
                    .addGroup(P_MembresiaOfertadorLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(P_MembresiaOfertadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(P_MembresiaOfertadorLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(61, 61, 61)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        P_MembresiaOfertadorLayout.setVerticalGroup(
            P_MembresiaOfertadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MembresiaOfertadorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addGap(52, 52, 52)
                .addGroup(P_MembresiaOfertadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel16)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout D_MembresiaOfertadorLayout = new javax.swing.GroupLayout(D_MembresiaOfertador.getContentPane());
        D_MembresiaOfertador.getContentPane().setLayout(D_MembresiaOfertadorLayout);
        D_MembresiaOfertadorLayout.setHorizontalGroup(
            D_MembresiaOfertadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_MembresiaOfertadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_MembresiaOfertador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_MembresiaOfertadorLayout.setVerticalGroup(
            D_MembresiaOfertadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_MembresiaOfertadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_MembresiaOfertador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_LogIn.setText("Log In");
        B_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_LogInMouseClicked(evt);
            }
        });
        B_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LogInActionPerformed(evt);
            }
        });

        L_SignIn.setText("Sign In");

        B_Register.setText("Registrarse");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(L_SignIn)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(L_SignIn)
                .addGap(93, 93, 93)
                .addComponent(B_LogIn)
                .addGap(69, 69, 69)
                .addComponent(B_Register)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_LogInMouseClicked
        D_LogIn.setVisible(true);
        
    }//GEN-LAST:event_B_LogInMouseClicked

    private void B_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_LogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_LogIn;
    private javax.swing.JButton B_Register;
    private javax.swing.JButton B_Register_RegisterNaA;
    private com.toedter.calendar.JDateChooser DC_Birthday_RegisterNaA;
    private javax.swing.JDialog D_LogIn;
    private javax.swing.JDialog D_MembresiaOfertador;
    private javax.swing.JDialog D_RegisterNaA;
    private javax.swing.JDialog D_RetrievePassword;
    private javax.swing.JLabel L_Nickname;
    private javax.swing.JList<String> L_PaisDeNacimiento_RegisterNaA;
    private javax.swing.JLabel L_Password_RetrievePassword;
    private javax.swing.JLabel L_SignIn;
    private javax.swing.JPasswordField PF_Password;
    private javax.swing.JPasswordField PF_password_RegisterNaA;
    private javax.swing.JPanel P_LogIn;
    private javax.swing.JPanel P_MembresiaOfertador;
    private javax.swing.JPanel P_RegisterNaA;
    private javax.swing.JPanel P_RetrievePassword;
    private javax.swing.JSpinner S_Usuario;
    private javax.swing.JSpinner S_Usuario_RegisterNaA;
    private javax.swing.JTextField TF_Correo_RegisterNaA;
    private javax.swing.JTextField TF_Correo_RetrievePassword;
    private javax.swing.JTextField TF_Nickname;
    private javax.swing.JTextField TF_Nickname_RegisterNaA;
    private javax.swing.JTextField TF_NombreCompleto_RegisterNaA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Cliente> clientes = new ArrayList<>();
}   
